### ISSUE TITLE
Running hello world fails

### ISSUE THREAD

**Issue by nanjekyejoannah** [SOM-st/PySOM#29]
```
jnanjeky@simplex:~/cascon1/PySOM$ ./som.sh -cp Smalltalk TestSuite/TestHarness.som
Object class could not be loaded. It is likely that the class path has not been initialized properly. Please make sure that the '-cp' parameter is given on the command-line.
jnanjeky@simplex:~/cascon1/PySOM$ 

```
Am I missing something?

**Comment by smarr** [comment]
Sorry, looks like the instructions are incomplete.
Before being able to run any program, you'll need to initialize the git submodule with the core library.

`git submodule update --init` should do the trick.

**Comment by nanjekyejoannah** [comment]
Thanks, it will help to include this in the readme. Thanks.
